### ISSUE TITLE
能不能增加中文界面？非常感谢，这个项目是非常成功的，简单而且高效，完美解决简单使用的目标。多谢。

### ISSUE THREAD

**Issue by zrwd01** [shuai132/ScopeGUI#4]
能不能增加中文界面？非常感谢，这个项目是非常成功的，简单而且高效，完美解决简单使用的目标。多谢。

**Comment by shuai132** [comment]
鉴于文字不多，而且中文渲染还要附带字体文件或者跨平台处理（二进制体积、加载速度都有点影响）。
英文更加清晰好看点，就不改了~
